// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: updateripc.proto

package ipcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_UNAUTHORIZED        ErrorCode = 1
	ErrorCode_ERROR_CODE_UNSUPPORTED_VERSION ErrorCode = 2
	ErrorCode_ERROR_CODE_BAD_REQUEST         ErrorCode = 3
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_UNAUTHORIZED",
		2: "ERROR_CODE_UNSUPPORTED_VERSION",
		3: "ERROR_CODE_BAD_REQUEST",
		4: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_UNAUTHORIZED":        1,
		"ERROR_CODE_UNSUPPORTED_VERSION": 2,
		"ERROR_CODE_BAD_REQUEST":         3,
		"ERROR_CODE_INTERNAL":            4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_updateripc_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_updateripc_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{0}
}

// ===== v2 (explicit handshake protocol) =====
//
// Every v2 message is written to the wire as
// [1-byte FrameType tag][4-byte big-endian length][protobuf bytes] — no
// Envelope/oneof wrapper. FRAME_TYPE_UNSPECIFIED (0) is RESERVED and must
// never be sent as a real tag: MaxFrameSize is 64KiB (65536), so a v1
// client's first wire byte — the most-significant byte of its 4-byte
// length prefix — is always 0x00 for any legacy-valid frame. A dual-protocol
// server therefore treats a first byte of 0x00 as unambiguously v1, and any
// other byte as a v2 FrameType tag. See emly-updater's internal/ipc/server.go
// handleConn and emly's backend/utils/updateripc/handshake.go requestV2.
//
// Exchange, one connection per session, in order:
//
//	ClientHello -> ServerAnswHello
//	ClientSemverSend -> ServerSemverOk | ServerSemverReject (closes on reject)
//	ServerRequestAuthChallenge -> ClientAuthResponse (closes on bad HMAC)
//	ClientSystemInfoRequest | ClientADStatusRequest
//	  -> ServerSystemInfoResponse | ServerADStatusResponse | (wraps ErrorResponse)
//
// The payload phase deliberately reuses SystemInfoRequest/SystemInfoResponse
// and ADStatusRequest/ADStatusResponse above as-is (already independent
// top-level messages, never nested inside Envelope's oneof) — tagging them
// directly avoids duplicating identical message shapes.
type FrameType int32

const (
	FrameType_FRAME_TYPE_UNSPECIFIED                   FrameType = 0 // reserved — legacy-protocol discriminator, never a real message
	FrameType_FRAME_TYPE_CLIENT_HELLO                  FrameType = 1
	FrameType_FRAME_TYPE_SERVER_ANSW_HELLO             FrameType = 2
	FrameType_FRAME_TYPE_CLIENT_SEMVER_SEND            FrameType = 3
	FrameType_FRAME_TYPE_SERVER_SEMVER_OK              FrameType = 4
	FrameType_FRAME_TYPE_SERVER_SEMVER_REJECT          FrameType = 5
	FrameType_FRAME_TYPE_SERVER_REQUEST_AUTH_CHALLENGE FrameType = 6
	FrameType_FRAME_TYPE_CLIENT_AUTH_RESPONSE          FrameType = 7
	FrameType_FRAME_TYPE_CLIENT_SYSTEM_INFO_REQUEST    FrameType = 8
	FrameType_FRAME_TYPE_SERVER_SYSTEM_INFO_RESPONSE   FrameType = 9
	FrameType_FRAME_TYPE_CLIENT_AD_STATUS_REQUEST      FrameType = 10
	FrameType_FRAME_TYPE_SERVER_AD_STATUS_RESPONSE     FrameType = 11
	FrameType_FRAME_TYPE_SERVER_ERROR                  FrameType = 12 // wraps ErrorResponse; any v2 rejection after ClientHello
)

// Enum value maps for FrameType.
var (
	FrameType_name = map[int32]string{
		0:  "FRAME_TYPE_UNSPECIFIED",
		1:  "FRAME_TYPE_CLIENT_HELLO",
		2:  "FRAME_TYPE_SERVER_ANSW_HELLO",
		3:  "FRAME_TYPE_CLIENT_SEMVER_SEND",
		4:  "FRAME_TYPE_SERVER_SEMVER_OK",
		5:  "FRAME_TYPE_SERVER_SEMVER_REJECT",
		6:  "FRAME_TYPE_SERVER_REQUEST_AUTH_CHALLENGE",
		7:  "FRAME_TYPE_CLIENT_AUTH_RESPONSE",
		8:  "FRAME_TYPE_CLIENT_SYSTEM_INFO_REQUEST",
		9:  "FRAME_TYPE_SERVER_SYSTEM_INFO_RESPONSE",
		10: "FRAME_TYPE_CLIENT_AD_STATUS_REQUEST",
		11: "FRAME_TYPE_SERVER_AD_STATUS_RESPONSE",
		12: "FRAME_TYPE_SERVER_ERROR",
	}
	FrameType_value = map[string]int32{
		"FRAME_TYPE_UNSPECIFIED":                   0,
		"FRAME_TYPE_CLIENT_HELLO":                  1,
		"FRAME_TYPE_SERVER_ANSW_HELLO":             2,
		"FRAME_TYPE_CLIENT_SEMVER_SEND":            3,
		"FRAME_TYPE_SERVER_SEMVER_OK":              4,
		"FRAME_TYPE_SERVER_SEMVER_REJECT":          5,
		"FRAME_TYPE_SERVER_REQUEST_AUTH_CHALLENGE": 6,
		"FRAME_TYPE_CLIENT_AUTH_RESPONSE":          7,
		"FRAME_TYPE_CLIENT_SYSTEM_INFO_REQUEST":    8,
		"FRAME_TYPE_SERVER_SYSTEM_INFO_RESPONSE":   9,
		"FRAME_TYPE_CLIENT_AD_STATUS_REQUEST":      10,
		"FRAME_TYPE_SERVER_AD_STATUS_RESPONSE":     11,
		"FRAME_TYPE_SERVER_ERROR":                  12,
	}
)

func (x FrameType) Enum() *FrameType {
	p := new(FrameType)
	*p = x
	return p
}

func (x FrameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameType) Descriptor() protoreflect.EnumDescriptor {
	return file_updateripc_proto_enumTypes[1].Descriptor()
}

func (FrameType) Type() protoreflect.EnumType {
	return &file_updateripc_proto_enumTypes[1]
}

func (x FrameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameType.Descriptor instead.
func (FrameType) EnumDescriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{1}
}

// Envelope is the single message written to and read from the pipe per
// exchange: one request Envelope in, one response Envelope out, then the
// connection closes.
type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Semver of the sending binary (EMLyUpdater on responses, EMLy on
	// requests) — never the wire protocol_version, which only tracks
	// schema/framing compatibility. Used by the receiving side to enforce
	// the min column of the compatibility matrix above.
	SenderVersion string `protobuf:"bytes,2,opt,name=sender_version,json=senderVersion,proto3" json:"sender_version,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_SystemInfoRequest
	//	*Envelope_SystemInfoResponse
	//	*Envelope_AdStatusRequest
	//	*Envelope_AdStatusResponse
	//	*Envelope_Error
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_updateripc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Envelope) GetSenderVersion() string {
	if x != nil {
		return x.SenderVersion
	}
	return ""
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetSystemInfoRequest() *SystemInfoRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SystemInfoRequest); ok {
			return x.SystemInfoRequest
		}
	}
	return nil
}

func (x *Envelope) GetSystemInfoResponse() *SystemInfoResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_SystemInfoResponse); ok {
			return x.SystemInfoResponse
		}
	}
	return nil
}

func (x *Envelope) GetAdStatusRequest() *ADStatusRequest {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AdStatusRequest); ok {
			return x.AdStatusRequest
		}
	}
	return nil
}

func (x *Envelope) GetAdStatusResponse() *ADStatusResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_AdStatusResponse); ok {
			return x.AdStatusResponse
		}
	}
	return nil
}

func (x *Envelope) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_SystemInfoRequest struct {
	SystemInfoRequest *SystemInfoRequest `protobuf:"bytes,10,opt,name=system_info_request,json=systemInfoRequest,proto3,oneof"`
}

type Envelope_SystemInfoResponse struct {
	SystemInfoResponse *SystemInfoResponse `protobuf:"bytes,11,opt,name=system_info_response,json=systemInfoResponse,proto3,oneof"`
}

type Envelope_AdStatusRequest struct {
	AdStatusRequest *ADStatusRequest `protobuf:"bytes,12,opt,name=ad_status_request,json=adStatusRequest,proto3,oneof"`
}

type Envelope_AdStatusResponse struct {
	AdStatusResponse *ADStatusResponse `protobuf:"bytes,13,opt,name=ad_status_response,json=adStatusResponse,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ErrorResponse `protobuf:"bytes,99,opt,name=error,proto3,oneof"`
}

func (*Envelope_SystemInfoRequest) isEnvelope_Body() {}

func (*Envelope_SystemInfoResponse) isEnvelope_Body() {}

func (*Envelope_AdStatusRequest) isEnvelope_Body() {}

func (*Envelope_AdStatusResponse) isEnvelope_Body() {}

func (*Envelope_Error) isEnvelope_Body() {}

type SystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoRequest) Reset() {
	*x = SystemInfoRequest{}
	mi := &file_updateripc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoRequest) ProtoMessage() {}

func (x *SystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoRequest.ProtoReflect.Descriptor instead.
func (*SystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{1}
}

type SystemInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Hwid          string                 `protobuf:"bytes,2,opt,name=hwid,proto3" json:"hwid,omitempty"`
	InternalIp    string                 `protobuf:"bytes,3,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemInfoResponse) Reset() {
	*x = SystemInfoResponse{}
	mi := &file_updateripc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfoResponse) ProtoMessage() {}

func (x *SystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfoResponse.ProtoReflect.Descriptor instead.
func (*SystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{2}
}

func (x *SystemInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemInfoResponse) GetHwid() string {
	if x != nil {
		return x.Hwid
	}
	return ""
}

func (x *SystemInfoResponse) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *SystemInfoResponse) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

type ADStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADStatusRequest) Reset() {
	*x = ADStatusRequest{}
	mi := &file_updateripc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADStatusRequest) ProtoMessage() {}

func (x *ADStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADStatusRequest.ProtoReflect.Descriptor instead.
func (*ADStatusRequest) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{3}
}

type ADStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdDomain      string                 `protobuf:"bytes,1,opt,name=ad_domain,json=adDomain,proto3" json:"ad_domain,omitempty"`
	DomainJoined  bool                   `protobuf:"varint,2,opt,name=domain_joined,json=domainJoined,proto3" json:"domain_joined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADStatusResponse) Reset() {
	*x = ADStatusResponse{}
	mi := &file_updateripc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADStatusResponse) ProtoMessage() {}

func (x *ADStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADStatusResponse.ProtoReflect.Descriptor instead.
func (*ADStatusResponse) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{4}
}

func (x *ADStatusResponse) GetAdDomain() string {
	if x != nil {
		return x.AdDomain
	}
	return ""
}

func (x *ADStatusResponse) GetDomainJoined() bool {
	if x != nil {
		return x.DomainJoined
	}
	return false
}

type ErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Code  ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=emly.updateripc.v1.ErrorCode" json:"code,omitempty"`
	// Generic only — never echoes a path or PID back to the client.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_updateripc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{5}
}

func (x *ErrorResponse) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // must equal 2
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_updateripc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{6}
}

func (x *ClientHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type ServerAnswHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // echoed, always 2
	ServerVersion   string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`        // EMLyUpdater's own semver
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServerAnswHello) Reset() {
	*x = ServerAnswHello{}
	mi := &file_updateripc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerAnswHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerAnswHello) ProtoMessage() {}

func (x *ServerAnswHello) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerAnswHello.ProtoReflect.Descriptor instead.
func (*ServerAnswHello) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{7}
}

func (x *ServerAnswHello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ServerAnswHello) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type ClientSemverSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientVersion string                 `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"` // EMLy's own semver
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSemverSend) Reset() {
	*x = ClientSemverSend{}
	mi := &file_updateripc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSemverSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSemverSend) ProtoMessage() {}

func (x *ClientSemverSend) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSemverSend.ProtoReflect.Descriptor instead.
func (*ClientSemverSend) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{8}
}

func (x *ClientSemverSend) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type ServerSemverOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSemverOk) Reset() {
	*x = ServerSemverOk{}
	mi := &file_updateripc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSemverOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSemverOk) ProtoMessage() {}

func (x *ServerSemverOk) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSemverOk.ProtoReflect.Descriptor instead.
func (*ServerSemverOk) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{9}
}

type ServerSemverReject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generic only — never echoes a path or PID back to the client.
	Reason        string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerSemverReject) Reset() {
	*x = ServerSemverReject{}
	mi := &file_updateripc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSemverReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSemverReject) ProtoMessage() {}

func (x *ServerSemverReject) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSemverReject.ProtoReflect.Descriptor instead.
func (*ServerSemverReject) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{10}
}

func (x *ServerSemverReject) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ServerRequestAuthChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 32 random bytes, crypto/rand
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequestAuthChallenge) Reset() {
	*x = ServerRequestAuthChallenge{}
	mi := &file_updateripc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequestAuthChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequestAuthChallenge) ProtoMessage() {}

func (x *ServerRequestAuthChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequestAuthChallenge.ProtoReflect.Descriptor instead.
func (*ServerRequestAuthChallenge) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{11}
}

func (x *ServerRequestAuthChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type ClientAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hmac          []byte                 `protobuf:"bytes,1,opt,name=hmac,proto3" json:"hmac,omitempty"` // HMAC-SHA256(sharedSecret, nonce)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientAuthResponse) Reset() {
	*x = ClientAuthResponse{}
	mi := &file_updateripc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthResponse) ProtoMessage() {}

func (x *ClientAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_updateripc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthResponse.ProtoReflect.Descriptor instead.
func (*ClientAuthResponse) Descriptor() ([]byte, []int) {
	return file_updateripc_proto_rawDescGZIP(), []int{12}
}

func (x *ClientAuthResponse) GetHmac() []byte {
	if x != nil {
		return x.Hmac
	}
	return nil
}

var File_updateripc_proto protoreflect.FileDescriptor

const file_updateripc_proto_rawDesc = "" +
	"\n" +
	"\x10updateripc.proto\x12\x12emly.updateripc.v1\"\xfd\x03\n" +
	"\bEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0esender_version\x18\x02 \x01(\tR\rsenderVersion\x12W\n" +
	"\x13system_info_request\x18\n" +
	" \x01(\v2%.emly.updateripc.v1.SystemInfoRequestH\x00R\x11systemInfoRequest\x12Z\n" +
	"\x14system_info_response\x18\v \x01(\v2&.emly.updateripc.v1.SystemInfoResponseH\x00R\x12systemInfoResponse\x12Q\n" +
	"\x11ad_status_request\x18\f \x01(\v2#.emly.updateripc.v1.ADStatusRequestH\x00R\x0fadStatusRequest\x12T\n" +
	"\x12ad_status_response\x18\r \x01(\v2$.emly.updateripc.v1.ADStatusResponseH\x00R\x10adStatusResponse\x129\n" +
	"\x05error\x18c \x01(\v2!.emly.updateripc.v1.ErrorResponseH\x00R\x05errorB\x06\n" +
	"\x04body\"\x13\n" +
	"\x11SystemInfoRequest\"\x84\x01\n" +
	"\x12SystemInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04hwid\x18\x02 \x01(\tR\x04hwid\x12\x1f\n" +
	"\vinternal_ip\x18\x03 \x01(\tR\n" +
	"internalIp\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\"\x11\n" +
	"\x0fADStatusRequest\"T\n" +
	"\x10ADStatusResponse\x12\x1b\n" +
	"\tad_domain\x18\x01 \x01(\tR\badDomain\x12#\n" +
	"\rdomain_joined\x18\x02 \x01(\bR\fdomainJoined\"\\\n" +
	"\rErrorResponse\x121\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1d.emly.updateripc.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\vClientHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\"c\n" +
	"\x0fServerAnswHello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\"9\n" +
	"\x10ClientSemverSend\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\"\x10\n" +
	"\x0eServerSemverOk\",\n" +
	"\x12ServerSemverReject\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"2\n" +
	"\x1aServerRequestAuthChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"(\n" +
	"\x12ClientAuthResponse\x12\x12\n" +
	"\x04hmac\x18\x01 \x01(\fR\x04hmac*\x9d\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x01\x12\"\n" +
	"\x1eERROR_CODE_UNSUPPORTED_VERSION\x10\x02\x12\x1a\n" +
	"\x16ERROR_CODE_BAD_REQUEST\x10\x03\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x04*\xe9\x03\n" +
	"\tFrameType\x12\x1a\n" +
	"\x16FRAME_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FRAME_TYPE_CLIENT_HELLO\x10\x01\x12 \n" +
	"\x1cFRAME_TYPE_SERVER_ANSW_HELLO\x10\x02\x12!\n" +
	"\x1dFRAME_TYPE_CLIENT_SEMVER_SEND\x10\x03\x12\x1f\n" +
	"\x1bFRAME_TYPE_SERVER_SEMVER_OK\x10\x04\x12#\n" +
	"\x1fFRAME_TYPE_SERVER_SEMVER_REJECT\x10\x05\x12,\n" +
	"(FRAME_TYPE_SERVER_REQUEST_AUTH_CHALLENGE\x10\x06\x12#\n" +
	"\x1fFRAME_TYPE_CLIENT_AUTH_RESPONSE\x10\a\x12)\n" +
	"%FRAME_TYPE_CLIENT_SYSTEM_INFO_REQUEST\x10\b\x12*\n" +
	"&FRAME_TYPE_SERVER_SYSTEM_INFO_RESPONSE\x10\t\x12'\n" +
	"#FRAME_TYPE_CLIENT_AD_STATUS_REQUEST\x10\n" +
	"\x12(\n" +
	"$FRAME_TYPE_SERVER_AD_STATUS_RESPONSE\x10\v\x12\x1b\n" +
	"\x17FRAME_TYPE_SERVER_ERROR\x10\fB\x15Z\x13emlyipc/ipcpb;ipcpbb\x06proto3"

var (
	file_updateripc_proto_rawDescOnce sync.Once
	file_updateripc_proto_rawDescData []byte
)

func file_updateripc_proto_rawDescGZIP() []byte {
	file_updateripc_proto_rawDescOnce.Do(func() {
		file_updateripc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_updateripc_proto_rawDesc), len(file_updateripc_proto_rawDesc)))
	})
	return file_updateripc_proto_rawDescData
}

var file_updateripc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_updateripc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_updateripc_proto_goTypes = []any{
	(ErrorCode)(0),                     // 0: emly.updateripc.v1.ErrorCode
	(FrameType)(0),                     // 1: emly.updateripc.v1.FrameType
	(*Envelope)(nil),                   // 2: emly.updateripc.v1.Envelope
	(*SystemInfoRequest)(nil),          // 3: emly.updateripc.v1.SystemInfoRequest
	(*SystemInfoResponse)(nil),         // 4: emly.updateripc.v1.SystemInfoResponse
	(*ADStatusRequest)(nil),            // 5: emly.updateripc.v1.ADStatusRequest
	(*ADStatusResponse)(nil),           // 6: emly.updateripc.v1.ADStatusResponse
	(*ErrorResponse)(nil),              // 7: emly.updateripc.v1.ErrorResponse
	(*ClientHello)(nil),                // 8: emly.updateripc.v1.ClientHello
	(*ServerAnswHello)(nil),            // 9: emly.updateripc.v1.ServerAnswHello
	(*ClientSemverSend)(nil),           // 10: emly.updateripc.v1.ClientSemverSend
	(*ServerSemverOk)(nil),             // 11: emly.updateripc.v1.ServerSemverOk
	(*ServerSemverReject)(nil),         // 12: emly.updateripc.v1.ServerSemverReject
	(*ServerRequestAuthChallenge)(nil), // 13: emly.updateripc.v1.ServerRequestAuthChallenge
	(*ClientAuthResponse)(nil),         // 14: emly.updateripc.v1.ClientAuthResponse
}
var file_updateripc_proto_depIdxs = []int32{
	3, // 0: emly.updateripc.v1.Envelope.system_info_request:type_name -> emly.updateripc.v1.SystemInfoRequest
	4, // 1: emly.updateripc.v1.Envelope.system_info_response:type_name -> emly.updateripc.v1.SystemInfoResponse
	5, // 2: emly.updateripc.v1.Envelope.ad_status_request:type_name -> emly.updateripc.v1.ADStatusRequest
	6, // 3: emly.updateripc.v1.Envelope.ad_status_response:type_name -> emly.updateripc.v1.ADStatusResponse
	7, // 4: emly.updateripc.v1.Envelope.error:type_name -> emly.updateripc.v1.ErrorResponse
	0, // 5: emly.updateripc.v1.ErrorResponse.code:type_name -> emly.updateripc.v1.ErrorCode
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_updateripc_proto_init() }
func file_updateripc_proto_init() {
	if File_updateripc_proto != nil {
		return
	}
	file_updateripc_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_SystemInfoRequest)(nil),
		(*Envelope_SystemInfoResponse)(nil),
		(*Envelope_AdStatusRequest)(nil),
		(*Envelope_AdStatusResponse)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_updateripc_proto_rawDesc), len(file_updateripc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_updateripc_proto_goTypes,
		DependencyIndexes: file_updateripc_proto_depIdxs,
		EnumInfos:         file_updateripc_proto_enumTypes,
		MessageInfos:      file_updateripc_proto_msgTypes,
	}.Build()
	File_updateripc_proto = out.File
	file_updateripc_proto_goTypes = nil
	file_updateripc_proto_depIdxs = nil
}
